export const usStates = [
    {id:"AL", label:"ALABAMA"},
    {id:"AK", label:"ALASKA"},
    {id:"AZ", label:"ARIZONA"},
    {id:"AR", label:"ARKANSAS"},
    {id:"CA", label:"CALIFORNIA"},
    {id:"CO", label:"COLORADO"},
    {id:"CT", label:"CONNECTICUT"},
    {id:"DE", label:"DELAWARE"},
    {id:"DC", label:"DISTRICT OF COLUMBIA"},
    {id:"FL", label:"FLORIDA"},
    {id:"GA", label:"GEORGIA"},
    {id:"HI", label:"HAWAII"},
    {id:"ID", label:"IDAHO"},
    {id:"IL", label:"ILLINOIS"},
    {id:"IN", label:"INDIANA"},
    {id:"IA", label:"IOWA"},
    {id:"KS", label:"KANSAS"},
    {id:"KY", label:"KENTUCKY"},
    {id:"LA", label:"LOUISIANA"},
    {id:"ME", label:"MAINE"},
    {id:"MD", label:"MARYLAND"},
    {id:"MA", label:"MASSACHUSETTS"},
    {id:"MI", label:"MICHIGAN"},
    {id:"MN", label:"MINNESOTA"},
    {id:"MS", label:"MISSISSIPPI"},
    {id:"MO", label:"MISSOURI"},
    {id:"MT", label:"MONTANA"},
    {id:"NE", label:"NEBRASKA"},
    {id:"NV", label:"NEVADA"},
    {id:"NH", label:"NEW HAMPSHIRE"},
    {id:"NJ", label:"NEW JERSEY"},
    {id:"NM", label:"NEW MEXICO"},
    {id:"NY", label:"NEW YORK"},
    {id:"NC", label:"NORTH CAROLINA"},
    {id:"ND", label:"NORTH DAKOTA"},
    {id:"OH", label:"OHIO"},
    {id:"OK", label:"OKLAHOMA"},
    {id:"OR", label:"OREGON"},
    {id:"PA", label:"PENNSYLVANIA"},
    {id:"RI", label:"RHODE ISLAND"},
    {id:"SC", label:"SOUTH CAROLINA"},
    {id:"SD", label:"SOUTH DAKOTA"},
    {id:"TN", label:"TENNESSEE"},
    {id:"TX", label:"TEXAS"},
    {id:"UT", label:"UTAH"},
    {id:"VT", label:"VERMONT"},
    {id:"VA", label:"VIRGINIA"},
    {id:"WA", label:"WASHINGTON"},
    {id:"WV", label:"WEST VIRGINIA"},
    {id:"WI", label:"WISCONSIN"},
    {id:"WY", label:"WYOMING"}];


    export const usStatesInfluencer = [
        {id:"", label:"ALL"},
        {id:"AL", label:"ALABAMA"},
        {id:"AK", label:"ALASKA"},
        {id:"AZ", label:"ARIZONA"},
        {id:"AR", label:"ARKANSAS"},
        {id:"CA", label:"CALIFORNIA"},
        {id:"CO", label:"COLORADO"},
        {id:"CT", label:"CONNECTICUT"},
        {id:"DE", label:"DELAWARE"},
        {id:"DC", label:"DISTRICT OF COLUMBIA"},
        {id:"FL", label:"FLORIDA"},
        {id:"GA", label:"GEORGIA"},
        {id:"HI", label:"HAWAII"},
        {id:"ID", label:"IDAHO"},
        {id:"IL", label:"ILLINOIS"},
        {id:"IN", label:"INDIANA"},
        {id:"IA", label:"IOWA"},
        {id:"KS", label:"KANSAS"},
        {id:"KY", label:"KENTUCKY"},
        {id:"LA", label:"LOUISIANA"},
        {id:"ME", label:"MAINE"},
        {id:"MD", label:"MARYLAND"},
        {id:"MA", label:"MASSACHUSETTS"},
        {id:"MI", label:"MICHIGAN"},
        {id:"MN", label:"MINNESOTA"},
        {id:"MS", label:"MISSISSIPPI"},
        {id:"MO", label:"MISSOURI"},
        {id:"MT", label:"MONTANA"},
        {id:"NE", label:"NEBRASKA"},
        {id:"NV", label:"NEVADA"},
        {id:"NH", label:"NEW HAMPSHIRE"},
        {id:"NJ", label:"NEW JERSEY"},
        {id:"NM", label:"NEW MEXICO"},
        {id:"NY", label:"NEW YORK"},
        {id:"NC", label:"NORTH CAROLINA"},
        {id:"ND", label:"NORTH DAKOTA"},
        {id:"OH", label:"OHIO"},
        {id:"OK", label:"OKLAHOMA"},
        {id:"OR", label:"OREGON"},
        {id:"PA", label:"PENNSYLVANIA"},
        {id:"RI", label:"RHODE ISLAND"},
        {id:"SC", label:"SOUTH CAROLINA"},
        {id:"SD", label:"SOUTH DAKOTA"},
        {id:"TN", label:"TENNESSEE"},
        {id:"TX", label:"TEXAS"},
        {id:"UT", label:"UTAH"},
        {id:"VT", label:"VERMONT"},
        {id:"VA", label:"VIRGINIA"},
        {id:"WA", label:"WASHINGTON"},
        {id:"WV", label:"WEST VIRGINIA"},
        {id:"WI", label:"WISCONSIN"},
        {id:"WY", label:"WYOMING"}];